= Paulo Jerônimo

Paulo Jerônimo é triatleta e maratonista amador. Também trabalha com tecnologia da informação (IT), liderando projetos de desenvolvimento de software e atuando como instrutor e palestrante. Durante suas corridas idealizou, no passado, alguns projetos que não colocou em prática. Agora retornou, com força, e resolveu iniciar de vez os projetos da equipe link:../../[IT Finishers]. Seu objetivo é provar a si mesmo que com fé em Deus, vontade, planejamento e muito trabalho, todo sonho pode ser alçandado, independente de seu tamanho.

A palavra `Finisher` nos dá um título, uma medalha, que se obtem ao cruzar a linha de chegada numa corrida. No contexto da equipe `IT Finishers` esta palavra também vale um troféu a cada projeto concluído com sucesso.

++++
<center>
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/wD3fayNfyF/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">É muito mais que um #título ... é #ser. #Ironman ( #triathlon ) = #qualidade e #estilo de #vida, #saúde, #energia, #disposição.</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Paulo Jerônimo (@paulojeronimo_) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-12-01T10:16:33+00:00">Dec 12, 2014 at 2:16am PST</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
</center>
++++

Em vários momentos de sua vida, Paulo Jerônimo foi `Finisher`. Algumas vezes, também abandonou projetos e lamentou-se de tê-lo feito. Dessa forma, e por mais esse motivo, resolveu montar o `IT Finishers` pois acredita que grandes sonhos não podem ser abandonados e precisam ser realizados. Sendo assim, a concretização de projetos no `IT Finishers` é mais que uma meta: é a conclusão de um projeto pessoal onde ele pretende demonstrar, para si mesmo, que com vontade, planejamento, disciplina, foco e trabalho, grandes obras são construídas.

Tendo já participado de várias provas corrida de 10k, 21k, 42k e dois Ironmans (um não concluído) ...

++++
<center>
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/cjpAPwtf5N/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">#medalhas: #maratona de #Curitiba 2009, #SaoPaulo 2010, #Floripa 2011, #Rio 2012, #Meio #Ironman 2012, #Ironman 2013.</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Paulo Jerônimo (@paulojeronimo_) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2013-08-03T15:57:46+00:00">Aug 8, 2013 at 8:57am PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
</center>
++++

\... Paulo Jerônimo já provou o gosto doce de vitórias ...

++++
<center>
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/aORATRtf04/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">The most #exciting and #incredible #moment of my first #ironman (2013/#Florianópolis/#Brazil): the #arrival with my #kids! Woooooooowwwww!!!!! 👏💪😁 #triathlon</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Paulo Jerônimo (@paulojeronimo_) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2013-06-06T15:41:13+00:00">Jun 6, 2013 at 8:41am PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
</center>
++++

\... e https://www.facebook.com/photo.php?fbid=757943984228558&set=pb.100000388908507.-2207520000.1420296572.&type=3&theater[o amargo de batalhas perdidas]. Apendeu com seus erros e está aqui para experimentar, novamente, em 2015, várias vitórias. Dentre as vitórias que pretende ter com o `IT Finishers`, está o desejo de fazer com que seus amigos de equipe ampliem ainda mais suas capacidades de organização e planejamento para a realização de seus sonhos.

Para esse ano (2015), Paulo Jerônimo, além de colocar projetos do `IT Finishers` em prática, tem planos de se inscrever (e inscrições realizadas) nas seguintes provas de corrida e/ou triatlo:

. 31/Jan - Corrida de Reis - Brasília - (TALVEZ)
. 08/Fev - Meia Maratona das Pontes - Brasília - (INSCRITO)
. 05/Abr - Meia Maratona Caixa - Brasília - (AGUARDANDO ABERTURA DAS INSCRIÇÕES)
. 26/Jul - Maratona do Rio - (INSCRITO)
. 29/Ago - Ironman 70.3 Foz do Iguaçu - (INSCRITO)
. 08/Nov - Ironman Fortaleza - (AGUARDANDO ABERTURA DAS INSCRIÇÕES)

Que seja um ótimo ano e de grandes vitórias! \o/

