= Projeto 3plans - release 0.1.0: calendário de provas
Paulo Jerônimo

O calendário de provas é um dos itens mais importantes para um atleta. Para corredores e/ou triatletas, a data de uma prova é o que dirige sua preparação pois, tendo como objetivo a participação numa prova, como uma meia maratona (21k) por exemplo, o atleta se programa através dessa data e de planilhas de treino com duração determinada. No meu caso, minha primeira meia maratona de 2015 será a http://www.meiamaratonadaspontes.com.br[Meia Maratona das Pontes], em Brasília/DF, que ocorrerá no dia 08 de fevereiro. Definida a data de início dos treinos (05/Jan) e tendo como meta a conclusão desta meia maratona num tempo inferior a 2h, estou seguindo uma http://revistacontrarelogio.com.br/materia/preparando-se-para-os-21-km-em-5-semanas-uma-proposta-de-treino-com-base-na-frequencia-cardiaca/[planilha de treino de cinco semanas]. Meu último dia de execução dessa planilha é, obviamente, o dia da prova.

A link:../../../../#_equipe[equipe IT Finishers] pensando na importância do calendário para o atleta, está iniciando a construção do projeto 3plans a partir dele. A idéia por trás da apresentação de um calendário no 3plans, porém, vai um pouco além de uma simples listagem de provas por data e nome. Começa dessa forma mas evolui, gradualmente, em novas versões, para algo maior.

O primeiro release do 3plans (0.1.0) possibilitará aos atletas a montagem de seu próprio calendário de provas. Para isso, o atleta selecionará, dentre uma lista de provas previamente cadastradas pelo administrador do sistema, as provas que ele tem a intenção de participar. Em seu calendário pessoal, o atleta também poderá selecionar se deseja tornar pública (ou não) a informação das provas que intenciona participar. Nesse primeiro release, também será disponibilizado pelo 3plans uma forma do atleta apresentar seu calendário público em qualquer site que desejar, de forma semelhante ao que é possível ser feito hoje, por exemplo, no http://instagram.com[Instagram], quando uma pessoa deseja colar uma foto pública de seu Instagram em alguma outra página como o seu próprio blog (exemplo).

Em resumo, o objetivo final desse primeiro release é tornar possível eu (assim como qualquer outro atleta) gerenciar e tornar público o meu próprio calendário de provas em link:../../../../equipe/paulojeronimo/[minha página pessoal no IT Finishers] ou em outra página HTML qualquer. Atualmente, eu já tenho link:../../../../equipe/paulojeronimo/#_metas[meu calendário publicado] mas, escrevendo-o, manualmente, nessa página. O que quero é buscar estas informações a partir do sistema 3plans.

Para exemplificar outros calendários de provas, posso citar os que estão disponíveis em vários sites nacionais e internacionais:

* Nacionais:
** http://runnersworld.abril.com.br/agenda/[Runners World]
** http://www.mksesportes.com.br/index.php?option=com_content&view=article&id=412:calendario-2015&catid=46:evento&Itemid=37[MKS Esportes (Brasília/DF)]
** http://www.nextrun.com.br/novo/?p=2080[Equipe NextRun (Brasília/DF)] 
** http://www.corce.org/calendario.html[CORCE - Corredores de Rua do Ceará]
** http://www.corpore.org.br/eve_calendariocorpore_2015.asp[Corpore]
** http://www.minhasinscricoes.com.br/sitemi/2010/[Minhas Inscrições]
* Internacionais:
** http://www.runningintheusa.com/Race/Calendar.aspx[Running in the USA]
** http://www.marathonguide.com/races/races.cfm?place=intl[Marathon Guide]
** http://uktriathlon.co.uk/tristore/286-triathlon-events-2015[UK Triathlon Store]
** http://www.active.com/triathlon[Active]
** http://www.halfmarathons.net/race-calendar/[Half Marathons]
** http://www.irishtriathlon.com/race-calendar-ireland/races/[Irish Triathlon]
** http://www.nyrr.org/races-and-events/2015[New York Road Runners]
** http://www.sportinglife.com/racing/calendar/2015/january[Sporting Life]
** http://www.trifind.com[TriFind]
** http://trimapper.com/triathlon-calendar/[TriMapper]
** http://runworcester.com/course/[Prova de 21k próximo a Boston (no período do RedHat Summit)]

Implicitamente, para nós do IT Finishers, a funcionalidade de oferecer um calendário particular para um atleta no 3plans inicia a construção de nossa base de atletas. Releases futuros do 3plans passarão a oferecer muitas outras funcionalidades, tanto para atletas quanto a patrocinadores do sistema.

== Outras funcinalidades

Também para esta release, implicitamente, são esperadas as seguintes funcionalidades:

* Sign up, Sign in e Sign out (do atleta);
* Gerenciamento da base de provas (apenas pelo administrador do sistema);
* Listagem (com vários filtros) de provas agendadas no mundo inteiro (utilizada pelo atleta para montar seu calendário);
** Filtros por:
*** Período
*** Nome de prova
*** Cidade/Estado/País
*** Tipo de prova (5k, 10k, 21k, 42k, Ironman 70.3, Ironman 140.6, etc)
* Sugestão de inclusão de prova (pelo atleta);
** Possibilita que o atleta sugira a administração do 3plans a inserção, em sua base, de uma prova identificada pelo atleta;

== Características não funcionais e/ou arquiteturais

Para este primeiro release também é esperado que:

* O frontend seja apenas em HTML 5, construído com o uso do https://angularjs.org[AngularJS];
** O suporte a tablets e smartphones, ainda que previsto, não será oferecido através de aplicações nativas (Android e/ou iOS);
* A aplicação esteja disponível para execução no https://www.openshift.com[OpenShift];
* O mecanismo de autenticação e autorização seja realizadas através do http://keycloak.jboss.org[Keycloak];
* Haja suporte para a execução tanto em desktops quanto smartphones;
* A aplicação seja internacionalizada suportando, inicialmente, as línguas português e inglês;
** O suporte a espanhol será oferecido num release futuro;
** http://blog.trifork.com/2014/04/10/internationalization-with-angularjs/[Post sobre internacionalização de aplicações AngularJS];

